export const hubTableData = [
    {
        img: 'https://o3swap.com/assets/images/hub/o3-pools-logo.png',
        name: 'O3 Pools',
        tvl: 154645.88,
        vol: 534.43,
        apr: 0,
    },
    {
        img: 'https://o3swap.com/assets/images/hub/usdt-pools-logo.png',
        name: 'USDT Pools',
        tvl: 19637.13,
        vol: 405.02,
        apr: 0,
    },
    {
        img: 'https://o3swap.com/assets/images/hub/usdc-pools-logo.png',
        name: 'USDC Pools',
        tvl: 29524.95,
        vol: 172.28,
        apr: 0,
    },
    {
        img: 'https://o3swap.com/assets/images/hub/eth-pools-logo.png',
        name: 'ETH Pools',
        tvl: 49538.19,
        vol: 24.66,
        apr: 0,
    },
    {
        img: 'https://o3swap.com/assets/images/hub/btc-pools-logo.png',
        name: 'BTC Pools',
        tvl: 11692.63,
        vol: 0,
        apr: 0,
    },
    {
        img: 'https://o3swap.com/assets/images/hub/brise-pools-logo.png',
        name: 'BRISE Pools',
        tvl: 19049.47,
        vol: 0,
        apr: 0,
    },
    {
        img: 'https://o3swap.com/assets/images/hub/matic-pools-logo.png',
        name: 'Matic Pools',
        tvl: 9227.57,
        vol: 172.28,
        apr: 0,
    },
    {
        img: 'https://o3swap.com/assets/images/hub/o3-pools-logo.png',
        name: 'USDC Pools',
        tvl: 29524.95,
        vol: 172.28,
        apr: 0,
    },
    {
        img: 'https://o3swap.com/assets/images/hub/o3-pools-logo.png',
        name: 'USDC Pools',
        tvl: 29524.95,
        vol: 172.28,
        apr: 0,
    },
    {
        img: 'https://o3swap.com/assets/images/hub/o3-pools-logo.png',
        name: 'USDC Pools',
        tvl: 29524.95,
        vol: 172.28,
        apr: 0,
    },
    {
        img: 'https://o3swap.com/assets/images/hub/o3-pools-logo.png',
        name: 'USDC Pools',
        tvl: 29524.95,
        vol: 172.28,
        apr: 0,
    },
    {
        img: 'https://o3swap.com/assets/images/hub/o3-pools-logo.png',
        name: 'USDC Pools',
        tvl: 29524.95,
        vol: 172.28,
        apr: 0,
    },
];
